### ISSUE TITLE
ValueError: unknown url type

### ISSUE THREAD

**Issue by itJunky** [dzhioev/vk_api_auth#4]
Взял как есть, импортнул vk_auth и воспользовался предложеным методом 
token, user_id = vk_auth.auth(phone, passwd, app_id, scope)

Traceback (most recent call last):
  File "./vkbrot.py", line 160, in <module>
    token, user_id = vk_auth.auth(phone, passwd, app_id, scope)
  File "/home/alp/vk_auth.py", line 96, in auth
    url = give_access(doc, opener)
  File "/home/alp/vk_auth.py", line 82, in give_access
    response = opener.open(parser.url, urllib.urlencode(parser.params))
  File "/usr/lib64/python2.6/urllib2.py", line 383, in open
    protocol = req.get_type()
  File "/usr/lib64/python2.6/urllib2.py", line 244, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /login?act=authcheck_code&hash=1443967155_b68d2e2115a342fec1

**Comment by itJunky** [comment]
Такое ощущение, что вместо URL пришли параметры

**Comment by tsyganov-ivan** [comment]
Последний коммит - 2 года назад)
с тех пор у вконтакта многое поменялось. Я перевел свои скрипты на https://github.com/dimka665/vk

**Comment by dzhioev** [comment]
На самом деле, все работало до недавних пор. Я посмотрю в чем проблема.

**Comment by tsyganov-ivan** [comment]
Все правильно, работает и сейчас.
Эта ситуация когда включена двухфакторная авторизация и нужно ввести код

**Comment by itJunky** [comment]
Да, я так и подумал про двухфакторку и уже отключил, но не помогло. И уже пытаюсь разобраться с модулем vk
